# Generated by Django 3.2.25 on 2024-07-03 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('income', models.CharField(blank=True, max_length=100)),
                ('horoscope', models.CharField(blank=True, max_length=100)),
                ('from_height', models.CharField(blank=True, max_length=100)),
                ('to_height', models.CharField(blank=True, max_length=100)),
                ('from_age', models.CharField(blank=True, max_length=100, null=True)),
                ('to_age', models.CharField(blank=True, max_length=100, null=True)),
                ('from_weight', models.CharField(blank=True, max_length=100)),
                ('to_weight', models.CharField(blank=True, max_length=100)),
                ('min_income', models.CharField(blank=True, max_length=100)),
                ('max_income', models.CharField(blank=True, max_length=100)),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.caste')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.religion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
