# Generated by Django 3.2.25 on 2024-07-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240704_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='caste_p',
            new_name='caste',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='religion_p',
            new_name='religion',
        ),
    ]
