# Generated by Django 3.2.25 on 2024-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240630_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drinking_habits',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='accounts.Hobby'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='smoking_habits',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50, null=True),
        ),
    ]
