# Generated by Django 3.2.25 on 2024-07-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240701_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.hobby'),
        ),
    ]
