# Generated by Django 3.2.25 on 2024-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20240701_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.TextField(blank=True, null=True),
        ),
    ]
