# Generated by Django 3.2.25 on 2024-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20240702_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='employementdetails',
            name='company_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employementdetails',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employementdetails',
            name='expertise_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=100, verbose_name='Expertise Level'),
        ),
    ]
