# Generated by Django 3.2.25 on 2024-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20240702_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employementdetails',
            name='seeking_job_title',
        ),
        migrations.AlterField(
            model_name='employementdetails',
            name='job_status',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Employer', 'Employer'), ('JobSeeker', 'JobSeeker')], max_length=100, verbose_name='Job Status'),
        ),
    ]
