# Generated by Django 3.2.25 on 2024-07-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20240702_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.TextField(blank=True, max_length=100, verbose_name='Address Line1')),
                ('address_line2', models.TextField(blank=True, max_length=100, verbose_name='Address Line2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=6, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, choices=[('IN', 'INDIA')], max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='user',
            name='company_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=100, verbose_name='Expertise Level'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_status',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Employer', 'Employer'), ('JobSeeker', 'JobSeeker')], max_length=100, verbose_name='Job Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.DeleteModel(
            name='EmployementDetails',
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
