# Generated by Django 3.2.25 on 2024-07-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20240702_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='caste',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.caste'),
        ),
        migrations.AlterField(
            model_name='family',
            name='religion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.religion'),
        ),
    ]
