# Generated by Django 3.2.25 on 2024-07-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20240702_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='family',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='family',
            name='user',
        ),
        migrations.DeleteModel(
            name='Caste',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
