# Generated by Django 3.2.25 on 2024-07-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reel',
            old_name='video',
            new_name='reel',
        ),
    ]
