# Generated by Django 3.2.25 on 2024-07-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_friend_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='friend_request',
            new_name='FriendRequest',
        ),
    ]
