# Generated by Django 3.2.25 on 2024-07-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='snapchat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
